# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tps <- function(ep, r) {
    .Call(`_mypackage_tps`, ep, r)
}

baseSVD <- function(X) {
    .Call(`_mypackage_baseSVD`, X)
}

dcSVD <- function(X) {
    .Call(`_mypackage_dcSVD`, X)
}

f1 <- function(x, y) {
    .Call(`_mypackage_f1`, x, y)
}

f2 <- function(x, y) {
    .Call(`_mypackage_f2`, x, y)
}

f3 <- function(x, y) {
    .Call(`_mypackage_f3`, x, y)
}

f4 <- function(x, y) {
    .Call(`_mypackage_f4`, x, y)
}

testfunction <- function(x, y) {
    .Call(`_mypackage_testfunction`, x, y)
}

meshgrid <- function(x, y, xv, yv) {
    invisible(.Call(`_mypackage_meshgrid`, x, y, xv, yv))
}

radialFunction <- function(r, RBFtype, R) {
    .Call(`_mypackage_radialFunction`, r, RBFtype, R)
}

DistanceMatrix <- function(dsites, ctrs) {
    .Call(`_mypackage_DistanceMatrix`, dsites, ctrs)
}

DistanceMatrix2 <- function(dsites, ctrs) {
    .Call(`_mypackage_DistanceMatrix2`, dsites, ctrs)
}

RBF_LS <- function(dsites, ctrs, RBFtype, R, neval) {
    .Call(`_mypackage_RBF_LS`, dsites, ctrs, RBFtype, R, neval)
}

RBF_LS2 <- function(y, dsites, ctrs, RBFtype, R, neval) {
    .Call(`_mypackage_RBF_LS2`, y, dsites, ctrs, RBFtype, R, neval)
}

RBF_LSP <- function(dsites, ctrs, RBFtype, R, neval, omega) {
    .Call(`_mypackage_RBF_LSP`, dsites, ctrs, RBFtype, R, neval, omega)
}

RBF_LSP2 <- function(y, dsites, ctrs, RBFtype, R, neval, omega) {
    .Call(`_mypackage_RBF_LSP2`, y, dsites, ctrs, RBFtype, R, neval, omega)
}

RBF_LSPSVD <- function(y, dsites, ctrs, RBFtype, R, neval, omega) {
    .Call(`_mypackage_RBF_LSPSVD`, y, dsites, ctrs, RBFtype, R, neval, omega)
}

